- platform: template
  sensors:
    battery_low:
      friendly_name: "Battery below treshold"
      value_template: >
        {% if is_state('binary_sensor.oneplus_a5010_is_charging', 'on') %}
          {{ False }}
        {% elif is_state('sensor.oneplus_a5010_battery_level', 'unknown') %}
          {{ False }}
        {% elif states('input_number.battery1')|int < states('sensor.oneplus_a5010_battery_level')|int %}
          {{ False }}
        {% else %}
          {{ True }}
        {% endif %}
