# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

mqtt:
  broker: !secret mqtt_broker
  port: 1883

switch: !include_dir_merge_list 'cfg.switch/'
input_select: !include_dir_merge_named 'cfg.input_select/'
automation: !include_dir_merge_list 'cfg.automation/'
script: !include_dir_merge_named 'cfg.script/'
