# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:    
  themes: !include_dir_merge_named themes
  
mqtt:
  broker: !secret mqtt_broker
  port: 1883

switch: !include_dir_merge_list 'cfg.switch/'
input_select: !include_dir_merge_named 'cfg.input_select/'
input_number: !include_dir_merge_named 'cfg.input_number/'
automation: !include_dir_merge_list 'cfg.automation/'
script: !include_dir_merge_named 'cfg.script/'
binary_sensor: !include_dir_merge_list 'cfg.binary_sensor/'
light: !include_dir_merge_list 'cfg.light/'
