- alias: "Set amp source to bluetooth"
  trigger:
    - platform: state
      entity_id: input_select.amp_source
      to: "Bluetooth"
  action:
    - service: script.select_amp_source
      data:
        repeat_count: 2

- alias: "Set amp source to optical"
  trigger:
    - platform: state
      entity_id: input_select.amp_source
      to: "Optical"
  action:
    - service: script.select_amp_source
      data:
        repeat_count: 4
