- platform: broadlink
  mac: !secret broadlink_mac
  switches:
    #SMSL AD18 amplifier 
    - name: "Amp power toggle"
      command_on: 'JgBYAAABIpYSExE5EhMSExI4EhMSExITERQSExE5EhMSOBM4ERQRFBE5EhMRFBEUERQRFBETEhQRExI4EjkSOBE5EjgSORE5EQAFjgABJ0wRAAxaAAEpTBIADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: 'JgBYAAABIpYSExE5EhMSExI4EhMSExITERQSExE5EhMSOBM4ERQRFBE5EhMRFBEUERQRFBETEhQRExI4EjkSOBE5EjgSORE5EQAFjgABJ0wRAAxaAAEpTBIADQUAAAAAAAAAAAAAAAAAAA=='
    - name: "Amp Volume up down"
      command_on: 'JgBQAAABIpYSExM3EhQRFBE5ERQRFBITERQSEhI5ERQSOBI4ERQSExITETkTEhITERQRFBEUERQRORITETkSOBI5ETkRORI4EwAFjQABKEsSAA0FAAAAAAAA'
      command_off: 'JgBQAAABI5YSExE5ExISExM4ERQRExITExISExM4EhMRORI4ExISExITETkTOBITEhMRFBEUERMSOREUERQRORE5EjgSORI4EgAFjwABJ0wTAA0FAAAAAAAA'
    - name: "Amp Volume up"
      command_on: 'JgBQAAABIpYSExM3EhQRFBE5ERQRFBITERQSEhI5ERQSOBI4ERQSExITETkTEhITERQRFBEUERQRORITETkSOBI5ETkRORI4EwAFjQABKEsSAA0FAAAAAAAA'
      command_off: 'JgBQAAABIpYSExM3EhQRFBE5ERQRFBITERQSEhI5ERQSOBI4ERQSExITETkTEhITERQRFBEUERQRORITETkSOBI5ETkRORI4EwAFjQABKEsSAA0FAAAAAAAA'
    - name: "Amp Volume down"
      command_on: 'JgBQAAABI5YSExE5ExISExM4ERQRExITExISExM4EhMRORI4ExISExITETkTOBITEhMRFBEUERMSOREUERQRORE5EjgSORI4EgAFjwABJ0wTAA0FAAAAAAAA'
      command_off: 'JgBQAAABI5YSExE5ExISExM4ERQRExITExISExM4EhMRORI4ExISExITETkTOBITEhMRFBEUERMSOREUERQRORE5EjgSORI4EgAFjwABJ0wTAA0FAAAAAAAA'
    - name: "Amp Menu toggle"
      command_on: 'JgBQAAABI5UTEhI4EhMSExM3EhMTEhITExITEhI4ExITOBE5ERQSExITERQSOBITEhMSExEUERQRORE5EhMSOBM4ETkSOBI4EwAFjQABKEwSAA0FAAAAAAAA'
      command_off: 'JgBQAAABI5UTEhI4EhMSExM3EhMTEhITExITEhI4ExITOBE5ERQSExITERQSOBITEhMSExEUERQRORE5EhMSOBM4ETkSOBI4EwAFjQABKEwSAA0FAAAAAAAA' 
    - name: "Amp Menu Left Right"
      command_on: 'JgBYAAABIpYTEhM4EhISFBE5ERQRFBEUERQSEhI5ERQRORI4ERQSExE5EzgRExITEhMSExITEhMSExITEjgTOBE5EjgRORI4EgAFjgABKUoSAAxdAAEnSxEADQUAAAAAAAAAAAAAAAAAAA=='
      command_off: 'JgBQAAABI5YRExI5EhMRFBI4ERQRFBEUERQSExE5ERQSOBI4EhMSExM3ExISOREUERQRFBEUEhMRFBE5EhMRORI4EjgTOBI4EQAFjwABKUoSAA0FAAAAAAAA'
    - name: "Amp Mute toggle"
      command_on: 'JgBQAAABJJUSExE5ERQRFBE5ERQRFBITEhMRFBE5EhMRORI4ExITEhI5ERQRFBE5ERQRFBEUERQRExM4ETkSExI4EjgSOBM4EQAFjgABKEsSAA0FAAAAAAAA'
      command_off: 'JgBQAAABJJUSExE5ERQRFBE5ERQRFBITEhMRFBE5EhMRORI4ExITEhI5ERQRFBE5ERQRFBEUERQRExM4ETkSExI4EjgSOBM4EQAFjgABKEsSAA0FAAAAAAAA'
    - name: "Amp Source cycle"
      command_on: 'JgBQAAABJJUTEhI5ERQSExE5ExITEhITEhMSExI5ERQRORI4ExITEhI5ETkSOBITEhMSExITEhMSExITEhMTOBE5ETkTOBI4EgAFkAABKUsRAA0FAAAAAAAA'
      command_off: 'JgBQAAABJJUTEhI5ERQSExE5ExITEhITEhMSExI5ERQRORI4ExITEhI5ETkSOBITEhMSExITEhMSExITEhMTOBE5ETkTOBI4EgAFkAABKUsRAA0FAAAAAAAA'
      
    #BenQ W1070+ projector
    - name: "Projector"
      command_on: 'JgDYAAABJZMUEhMSFBEUEhMSFBEUEhMSExIWEBMSExIUNxM3FBITEhQ2FDcUNhQ3FBITEhM3FBITEhQRFBITEhQ2FDcUERQ3EwAF6gABKZQUERQSExITEhQSExITEhQRFBITEhQRFBITNxQ3ExIUEhM3FDcTNxQ3ExIUERQ3FBEUEhMSFBEUEhM3FDcTEhQ2FAAF6QABKpQTEhMSFBEUEhMSFBEUEhMSFBEUEhMSFBEUNxM3FBITEhQ2FDcUNxM3FBEUEhM3FBITEhQRFBITEhM3FDcUERQ3EwANBQAAAAAAAAAAAAAAAAAA'
      command_off: 'JgCQAAABJJQUERQSExIUERQSExIUERQSExIUERQSExIUNhQ3FBEUEhMSFDYUNxQ3ExIUERQ3ExIUNxMSFBEUEhM3FDcTEhQ2FAAF6QABKpMUEhMSFBEUEhMSFBEUEhMSExIUERQSExIUNxM3FBEUEhMSFDcTNxQ3ExIUERQ3FBEUNxMSFBEUEhM3FDcTEhQ3EwANBQAAAAAAAA=='
    - name: "Projector mute toggle"
      command_on: 'JgCQAAABJJQTExMSExIUEhMSExITExMSExITExMSExITOBM3ExMTEhMSExMTNxMTETkSExMTExITOBM3ExMRORMSEzgRORI5EQAF7AABKZQRFBIUExIRFBMTERQRFBEUExMTEhEUEhQRORI5ERQRFBMTERQRORIUETkSFBMSERQSORE5EhQRORIUEzcSORE5EQANBQAAAAAAAA=='
      command_off: 'JgCQAAABJJQTExMSExIUEhMSExITExMSExITExMSExITOBM3ExMTEhMSExMTNxMTETkSExMTExITOBM3ExMRORMSEzgRORI5EQAF7AABKZQRFBIUExIRFBMTERQRFBEUExMTEhEUEhQRORI5ERQRFBMTERQRORIUETkSFBMSERQSORE5EhQRORIUEzcSORE5EQANBQAAAAAAAA=='
      
    #ILife A4 vacuum
    - name: "Vacuum"
      command_on: 'JgBIAAABHpURExETERQRFBAVEBQROBEUEDkRFBA5ERQROBAVEDkRFBAUEBUQORETERQQFRE4ERQQORA5ERQQORE4ETkQFRA4EQANBQAAAAAAAAAAAAAAAAAA'
      command_off: 'JgBIAAABHZUQFRAUERMRFBAVEBUQOBITETgRFBE4ERQROBAVEDkRExE5EBUQFBETETkQFRAUERMRFBE4ETkQORETETkQOBE5EQANBQAAAAAAAAAAAAAAAAAA'
